#
# travis (http://travis-ci.org/)
#  build description 
#   for portz (https://github.com/zbigg/portz)
#

language: cpp

branches:
  only:
    - master

before_script:
  - git submodule update --init
  - autoconf
  - ./configure

script:
  - make
  - make distcheck

