#
# travis (http://travis-ci.org/)
#  build description 
#   for portz (https://github.com/zbigg/portz)
#

install: make autoconf aclocal wget

branches:
  only:
    - master

before_script:
  - git clone https://github.com/zbigg/makefoo.git makefoo-master
  - git clone https://github.com/zbigg/bashfoo.git bashfoo
  - aclocal -I ./makefoo-master
  - autoheader
  - autoconf
  - ./configure --with-makefoo-dir=./makefoo-master

script:
  - make
  - make distcheck

